#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Civis Client documentation build configuration file, created by
# sphinx-quickstart on Tue Sep 15 11:15:53 2015.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import builtins
import glob
import inspect
import os
import datetime

# Set __sphinx_build__ before we import "civis", so that within the "civis" namespace,
# we can tell whether we're running the Sphinx doc build or not.
# https://stackoverflow.com/a/65147676
builtins.__sphinx_build__ = True

import civis  # noqa: E402

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "numpydoc.numpydoc",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.doctest",
    "sphinx.ext.intersphinx",
    "sphinx.ext.viewcode",
]

autosummary_generate = True

intersphinx_mapping = {
    "pandas": ("https://pandas.pydata.org/pandas-docs/stable", None),
    "python": ("https://docs.python.org/3", None),
    "requests": ("https://requests.readthedocs.io/en/latest/", None),
    "sklearn": ("https://scikit-learn.org/stable", None),
    "joblib": ("https://joblib.readthedocs.io/en/latest/", None),
    "tenacity": ("https://tenacity.readthedocs.io/en/latest/", None),
    "polars": ("https://docs.pola.rs/api/python/stable/", None),
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The encoding of source files.
# source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = "index"

# General information about the project.
current_year = datetime.datetime.now().year
project = "Civis API Python Client"
copyright = "2016-%d, Civis Analytics" % current_year
author = "Civis Analytics"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
major_version, minor_version, _ = civis.__version__.split(".")
# The short X.Y version.
version = "%s.%s" % (major_version, minor_version)
# The full version, including alpha/beta/rc tags.
release = civis.__version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''
# Else, today_fmt is used as the format for a strftime call.
# today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = []

# The reST default role (used for this markup: `text`) to use for all
# documents.
# default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
# add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
# add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
# show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
# keep_warnings = False

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# Keep numpydoc from adding ":toctree:" to the "Methods" summary tables it generates.
# Besides being noisy, that would make it ask sphinx.ext.autosummary for ~900 stub
# pages that autosummary can't generate: its stub generator scans rst *source* for
# ".. autosummary::" and never sees the directives numpydoc injects at build time.
numpydoc_class_members_toctree = False

# -- Options for HTML output ----------------------------------------------

html_theme = "sphinx_rtd_theme"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
    # Stop the sidebar navigation one level above the individual endpoint method
    # pages. The theme's default of 4 puts a copy of the endpoint's entire method
    # list (219 entries for /scripts) into the sidebar of every one of that
    # endpoint's method pages, which is more than half of the built HTML and swamps
    # the content on pages that exist precisely to be small. The methods are still
    # reachable from the "Methods" table on the endpoint page, and breadcrumbs and
    # prev/next links are unaffected.
    "navigation_depth": 3,
}

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
# html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
# html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = "_static/civis.svg"

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = "_static/civis.ico"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
# html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
# html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
# html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
# html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
# html_additional_pages = {}

# If false, no module index is generated.
# html_domain_indices = True

# If false, no index is generated.
# html_use_index = True

# If true, the index is split into individual pages for each letter.
# html_split_index = False

# If true, links to the reST sources are added to the pages.
# html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
# html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
# html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
# html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
# html_file_suffix = None

# Language to be used for generating the HTML full-text search index.
# Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'h', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'r', 'sv', 'tr'
# html_search_language = 'en'

# A dictionary with options for the search language support, empty by default.
# Now only 'ja' uses this config value
# html_search_options = {'type': 'default'}

# The name of a javascript file (relative to the configuration directory) that
# implements a search results scorer. If empty, the default will be used.
# html_search_scorer = 'scorer.js'

# Output file base name for HTML help builder.
htmlhelp_basename = "CivisClientdoc"

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    # 'preamble': '',
    # Latex figure (float) alignment
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        "CivisClient.tex",
        "Civis Client Documentation",
        "Civis Analytics",
        "manual",
    ),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
# latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
# latex_use_parts = False

# If true, show page references after internal links.
# latex_show_pagerefs = False

# If true, show URL addresses after external links.
# latex_show_urls = False

# Documents to append as an appendix to all manuals.
# latex_appendices = []

# If false, no module index is generated.
# latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "civisclient", "Civis Client Documentation", [author], 1)]

# If true, show URL addresses after external links.
# man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "CivisClient",
        "Civis Client Documentation",
        author,
        "CivisClient",
        "One line description of project.",
        "Miscellaneous",
    ),
]

# Documents to append as an appendix to all manuals.
# texinfo_appendices = []

# If false, no module index is generated.
# texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
# texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
# texinfo_no_detailmenu = False

nitpick_ignore = [
    ("envvar", "CIVIS_API_KEY"),
    ("py:class", "concurrent.futures._base.Future"),
    ("py:class", "civis.base.CivisAsyncResultBase"),
]
# Show tables of functions for each Resource class.
numpydoc_show_class_members = True

# Preserve signatures of a few methods wrapped with lru_cache. Need to set
# this before we import civis. See https://stackoverflow.com/a/28371786.
import functools  # noqa: E402


def noop_lru_cache(*args, **kwargs):
    def wrapper(func):
        def f(*args, **kwargs):
            return func(*args, **kwargs)

        f.__doc__ = func.__doc__
        f.__signature__ = inspect.signature(func)
        return f

    return wrapper


functools.lru_cache = noop_lru_cache


# Special functionality to accommodate autogenerated client.
def _make_attr_docs(class_names, module_path):
    doc = "\n    Attributes\n    ----------\n"
    doc_fmt = "    {}\n        An instance of the {} endpoint\n"
    for name in class_names:
        ref_link = ":class:`~{}.{}`".format(module_path, name.title())
        doc += doc_fmt.format(name, ref_link)
    return doc


def _attach_classes_to_module(module, class_data):
    for class_name, klass in class_data.items():
        # Modify the endpoint method's return annotaiton, so that in the compiled
        # Sphinx docs we show the user-friendly Response or Paginated instead of
        # something like _ResponseScriptsList.
        for name, method in vars(klass).items():
            if name.startswith("_"):
                continue
            signature = inspect.signature(method)
            if signature.return_annotation.__name__ == "Iterator":
                new_return_anno = civis.ListResponse | civis.PaginatedResponse
            elif method.__name__.startswith("list"):
                new_return_anno = civis.ListResponse
            else:
                new_return_anno = civis.Response
            method.__signature__ = signature.replace(return_annotation=new_return_anno)
            setattr(klass, name, method)
        setattr(module, class_name.title(), klass)


_API_RESOURCES_HEADER = (
    ".. _api_resources:\n\n"
    "API Resources\n"
    "=============\n\n"
    ".. note::\n\n"
    "   The API resources listed in this documentation are those for "
    "   a standard Civis Platform user. "
    "   Particular users may have access to resources and/or "
    "   methods that are featured-flagged or still under development and "
    "   therefore do not appear in this documentation. "
    "   For the exact API resources and methods available to a given "
    "   Civis Platform user, log on as that user and go to "
    "   https://api.civisanalytics.com.\n\n"
    ".. toctree::\n"
    "   :titlesonly:\n\n"
)

# Each endpoint page is only an index: the class docstring plus the "Methods" summary
# table that numpydoc injects (because numpydoc_show_class_members is on). Deliberately
# *no* ``:members:`` here -- the full documentation of every method lives on its own
# page, so that e.g. the /scripts endpoint page stays a few dozen KB instead of the
# 2 MB it used to be with all 200+ methods inlined.
_ENDPOINT_FMT = (
    ".. _{label}:\n\n"
    "{title}\n"
    "{underline}\n\n"
    ".. autoclass:: {full_path}\n"
    "   :exclude-members: __init__\n\n"
    ".. toctree::\n"
    "   :hidden:\n\n"
    "{toctree_entries}\n"
)

# One page per endpoint method. The title is what a user actually types, and the
# ``automethod`` keeps the cross-reference target at
# ``civis.resources._resources.<Endpoint>.<method>`` so that the summary table on the
# endpoint page (and any other cross-reference) resolves to this page.
_METHOD_FMT = (
    ".. _{label}:\n\n"
    "{title}\n"
    "{underline}\n\n"
    "A method of the :ref:`{endpoint_label}` endpoint.\n\n"
    ".. automethod:: {full_path}.{method_name}\n"
)

_DOCS_DIR = os.path.dirname(os.path.abspath(__file__))


def _method_names(klass):
    """Public method names of an auto-generated endpoint class.

    This must match numpydoc's own introspection
    (``numpydoc.docscrape.ClassDoc.methods``, i.e. ``sorted(inspect.getmembers(cls))``
    filtered down to public callables), because numpydoc -- not this file -- renders
    the "Methods" summary table on the endpoint page, and every row of that table
    needs a per-method page to link to.
    """
    return sorted(
        name
        for name, member in inspect.getmembers(klass)
        if not name.startswith("_") and callable(member)
    )


def _method_dir(base_path):
    return os.path.join(_DOCS_DIR, f"api_{base_path}")


def _write_if_changed(path, content):
    """Write ``content`` to ``path``, but only if that would change the file.

    This file generates ~950 rst files. Rewriting them all unconditionally would bump
    their mtimes and force Sphinx to re-read every document on every build, so an
    incremental rebuild would never be cheap.
    """
    try:
        with open(path) as existing_file:
            if existing_file.read() == content:
                return
    except FileNotFoundError:
        pass
    with open(path, "w") as new_file:
        new_file.write(content)


def _remove_stale_method_rst(expected_paths):
    """Delete per-method rst files left over from an earlier doc build.

    An API spec update can remove or rename methods, and a leftover page for a method
    that no longer exists would still be picked up by Sphinx, which would then warn
    about a missing attribute. Only ``*.rst`` files and then-empty directories are
    removed, so an unrelated directory that happens to match ``api_*`` is left alone.
    """
    for dir_path in glob.glob(os.path.join(_DOCS_DIR, "api_*")):
        if not os.path.isdir(dir_path):
            continue
        for rst_path in glob.glob(os.path.join(dir_path, "*.rst")):
            if rst_path not in expected_paths:
                os.remove(rst_path)
        if not os.listdir(dir_path):
            os.rmdir(dir_path)


def _write_method_rst(base_path, endpoint_name, method_name, civis_module):
    title = f"client.{base_path}.{method_name}"
    path = os.path.join(_method_dir(base_path), f"{method_name}.rst")
    _write_if_changed(
        path,
        _METHOD_FMT.format(
            label=f"api_{base_path}_{method_name}",
            title=title,
            underline="=" * len(title),
            endpoint_label=f"api_{base_path}_endpoint",
            full_path=".".join((civis_module, endpoint_name)),
            method_name=method_name,
        ),
    )
    return path


def _write_resources_rst(class_names, filename, civis_module, class_data):
    resources_rst = _API_RESOURCES_HEADER
    expected_method_rst = set()
    for class_name in class_names:
        endpoint_rst_filename_no_ext = f"api_{class_name.lower()}_endpoint"
        resources_rst += f"   {endpoint_rst_filename_no_ext}\n"
        endpoint_name = class_name.title()
        title = endpoint_name.replace("Json", "JSON").replace("_", " ")
        method_names = _method_names(class_data[class_name])
        os.makedirs(_method_dir(class_name), exist_ok=True)
        _write_if_changed(
            os.path.join(_DOCS_DIR, f"{endpoint_rst_filename_no_ext}.rst"),
            _ENDPOINT_FMT.format(
                label=endpoint_rst_filename_no_ext,
                title=title,
                # The heading text isn't the class name, so the underline has to be
                # as long as the text (e.g. "JSON Values"), not as long as
                # "Json_Values".
                underline="=" * len(title),
                full_path=".".join((civis_module, endpoint_name)),
                toctree_entries="\n".join(
                    f"   api_{class_name}/{method_name}" for method_name in method_names
                ),
            ),
        )
        for method_name in method_names:
            expected_method_rst.add(
                _write_method_rst(class_name, endpoint_name, method_name, civis_module)
            )
    _write_if_changed(os.path.join(_DOCS_DIR, filename), resources_rst)
    _remove_stale_method_rst(expected_method_rst)


def _write_hide_endpoint_class_sig_css(class_names):
    css_path = os.path.join(
        os.path.dirname(__file__), "_static", "hide_endpoint_class_sig.css"
    )
    with open(css_path, "w") as css_file:
        for class_name in class_names:
            camel_case = class_name.title()
            css_file.write(
                f"dt#civis\\.resources\\._resources\\.{camel_case}.sig.sig-object.py {{\n"  # noqa: E501
                "    display: none;\n"
                "}\n"
            )


_generated_attach_point = civis.resources._resources
_generated_attach_path = "civis.resources._resources"
_rst_basename = "api_resources.rst"

if os.getenv("FETCH_REMOTE_RESOURCES", "false").lower() == "true":
    api_key = os.environ.get("CIVIS_API_KEY")
    api_version = "1.0"
    extra_classes = civis.resources._resources.generate_classes(
        api_key=api_key, api_version=api_version
    )
else:
    import json
    from collections import OrderedDict
    from jsonref import JsonRef
    from civis.resources import API_SPEC_PATH

    with open(API_SPEC_PATH) as _raw:
        api_spec = JsonRef.replace_refs(json.load(_raw, object_pairs_hook=OrderedDict))
    extra_classes = civis.resources._resources.parse_api_spec(api_spec, "1.0")

sorted_class_names = sorted(extra_classes.keys())

civis.APIClient.__doc__ += _make_attr_docs(sorted_class_names, _generated_attach_path)

# TODO: The API endpoint doc details are in the stub file civis/client.pyi,
#   but Sphinx still doesn't really support stub files
#   (see https://github.com/sphinx-doc/sphinx/pull/4824 and
#   https://github.com/sphinx-doc/sphinx/issues/7630).
#   If Sphinx supports stub files in the future,
#   we can consider using civis/client.pyi to document the API endpoints
#   instead of having to fake-attach the endpoint classes to a module.
_attach_classes_to_module(_generated_attach_point, extra_classes)
_write_resources_rst(
    sorted_class_names, _rst_basename, _generated_attach_path, extra_classes
)
_write_hide_endpoint_class_sig_css(sorted_class_names)

# We fake-attached all of the autogenerated classes to
# civis.resources._resources, but we don't want them to appear in the docs with
# that as the module name (since they can't actually be imported from there).
# There is a global `add_module_name` parameter that we want to set to False
# for the autogenerated classes only. This needs to be done at the `Domain`
# level since that is where the rst is actually parsed into nodes.
from sphinx import addnodes  # noqa: E402
from sphinx.domains.python import PythonDomain, PyClasslike, PyMethod  # noqa: E402

_extra_class_titles = [klass.title() for klass in extra_classes.keys()]


class MaybeHiddenModulePyClasslike(PyClasslike):

    def handle_signature(self, sig, signode):
        add_module_orig = self.env.config.add_module_names
        # Is this an autogenerated class?
        toggle = (
            any(sig.startswith(title) for title in _extra_class_titles)
            and "session" in sig
            and "return_type" in sig
        )
        if toggle:
            self.env.config.add_module_names = False
        result = super().handle_signature(sig, signode)
        self.env.config.add_module_names = add_module_orig
        return result


PythonDomain.directives["class"] = MaybeHiddenModulePyClasslike


# The same problem as above, one level down. Now that each endpoint method has its own
# page, its `automethod` is no longer nested inside the endpoint's `autoclass`, so
# Sphinx no longer strips the class name from the signature and renders
# "Scripts.get(...)" instead of "get(...)". That prefix is misleading (again, the class
# can't be imported from that module) and it disagrees with the page title,
# "client.scripts.get", so drop the node. The cross-reference target is built from the
# directive's `:module:` option and the signature text rather than from what gets
# rendered, so it stays civis.resources._resources.Scripts.get.
class MaybeHiddenClassPyMethod(PyMethod):

    def handle_signature(self, sig, signode):
        result = super().handle_signature(sig, signode)
        # Is this a method of an autogenerated endpoint class?
        toggle = self.options.get("module") == _generated_attach_path and any(
            sig.startswith(f"{title}.") for title in _extra_class_titles
        )
        if toggle:
            for node in list(signode.findall(addnodes.desc_addname)):
                signode.remove(node)
        return result


PythonDomain.directives["method"] = MaybeHiddenClassPyMethod


def setup(app):
    app.add_css_file("custom.css")
    app.add_css_file("hide_endpoint_class_sig.css")
